### ISSUE TITLE
Blank Page

### ISSUE THREAD

**Issue by ayublin** [billyvg/pokemon-journal#1]
Hello I tried running the electron app release for darwin, but I am getting a blank page:

![image](https://cloud.githubusercontent.com/assets/1355215/17118951/58178df8-52ed-11e6-92bf-71c1af12325f.png)

Then I tried cloning the source and do npm install + run, getting the same issue, but now I can see this error:

![image](https://cloud.githubusercontent.com/assets/1355215/17118977/7604a4cc-52ed-11e6-8e0b-830663f56c58.png)

Any advice?

**Comment by Tivoli** [comment]
Which version of node are you using? Might need to use 6.3.0 and not 6.3.1 locally since electron is built against 6.3.0 currently.

**Comment by billyvg** [comment]
Ugh, I was using node stable (5.12.0), wiped `node_modules` and used `nvm` to test with 6.3.0 and am now getting the same issues. Switched back to 5.12.0 and getting it now too. Will try to see what's going on.

**Comment by ayublin** [comment]
Uh oh, I changed my node version to 6.3.0 but still seeing the issue. Thanks @billyvg, I have tried searching for solution but I am not familiar node JS, I will keep an eye on this.

**Comment by billyvg** [comment]
Ok, I found the package that was causing issues, this is fixed now.

**Comment by ayublin** [comment]
Thanks man, I can confirm that this is fixed now, nice tool btw!
