### ISSUE TITLE
'no such file or directory' error running 'npm run dev'

### ISSUE THREAD

**Issue by MaaRak** [billyvg/pokemon-journal#10]
Win10, node 4.4.7, npm 3.10.5:

Launched 'npm run dev', saw the following error while launching:

---

[0] > pokemon-journal@0.0.3 hot-server C:\Users\Matt\Desktop\pokemon-journal-0.0.3
[0] > node -r babel-register server.js
[0]
[1] fs.js:549
[1]   return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
[1]                  ^
[1]
[1] Error: ENOENT: no such file or directory, open 'C:\Users\Matt\Desktop\pokemon-journal-0.0.3\node_modules\electron-prebuilt\path.txt'
[1]     at Error (native)
[1]     at Object.fs.openSync (fs.js:549:18)
[1]     at Object.fs.readFileSync (fs.js:397:15)
[1]     at Object.<anonymous> (C:\Users\Matt\Desktop\pokemon-journal-0.0.3\node_modules\electron-prebuilt\index.js:4:42)
[1]     at Module._compile (module.js:409:26)
[1]     at Object.Module._extensions..js (module.js:416:10)
[1]     at Module.load (module.js:343:32)
[1]     at Function.Module._load (module.js:300:12)
[1]     at Module.require (module.js:353:17)
[1]     at require (internal/module.js:12:17)
[1]
[1] npm
[1]  ERR! Windows_NT 10.0.10586
[1] npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Users\Matt\Desktop\pokemon-journal-0.0.3\node_modules\npm\bin\npm-cli.js" "run" "start-hot"

---

contents of 'npm-debug.log':

---

0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
1 verbose cli   'C:\Users\Matt\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@3.10.5
3 info using node@v4.4.7
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle pokemon-journal@0.0.3~predev: pokemon-journal@0.0.3
6 silly lifecycle pokemon-journal@0.0.3~predev: no script for predev, continuing
7 info lifecycle pokemon-journal@0.0.3~dev: pokemon-journal@0.0.3
8 verbose lifecycle pokemon-journal@0.0.3~dev: unsafe-perm in lifecycle true
9 verbose lifecycle pokemon-journal@0.0.3~dev: PATH: C:\Users\Matt\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\Matt\Desktop\pokemon-journal-0.0.3\node_modules.bin;C:\Program Files\nodejs;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\nodejs\;C:\Users\Matt\AppData\Roaming\npm;c:\python27
10 verbose lifecycle pokemon-journal@0.0.3~dev: CWD: C:\Users\Matt\Desktop\pokemon-journal-0.0.3
11 silly lifecycle pokemon-journal@0.0.3~dev: Args: [ '/d /s /c',
11 silly lifecycle   'concurrently --kill-others "npm run hot-server" "npm run start-hot"' ]
12 silly lifecycle pokemon-journal@0.0.3~dev: Returned: code: 1  signal: null
13 info lifecycle pokemon-journal@0.0.3~dev: Failed to exec dev script
14 verbose stack Error: pokemon-journal@0.0.3 dev: `concurrently --kill-others "npm run hot-server" "npm run start-hot"`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\Matt\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\Matt\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:827:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid pokemon-journal@0.0.3
16 verbose cwd C:\Users\Matt\Desktop\pokemon-journal-0.0.3
17 error Windows_NT 10.0.10586
18 error argv "C:\Program Files\nodejs\node.exe" "C:\Users\Matt\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "run" "dev"
19 error node v4.4.7
20 error npm  v3.10.5
21 error code ELIFECYCLE
22 error pokemon-journal@0.0.3 dev: `concurrently --kill-others "npm run hot-server" "npm run start-hot"`
22 error Exit status 1
23 error Failed at the pokemon-journal@0.0.3 dev script 'concurrently --kill-others "npm run hot-server" "npm run start-hot"'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the pokemon-journal package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     concurrently --kill-others "npm run hot-server" "npm run start-hot"
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs pokemon-journal
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls pokemon-journal
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

---

**Comment by LightAMV** [comment]
Need help too!

**Comment by Tivoli** [comment]
Can you try it with Node 6.3? Electron uses version 6.3, you should be able to download it from https://nodejs.org

**Comment by MaaRak** [comment]
Installed Node 6.3.1, same error. However, after digging a little more on the electron-prebuilt issue I found [this](https://github.com/electron-userland/electron-prebuilt/issues/76#issuecomment-191259022) suggestion and it worked, the app opens now. Thanks!
