### ISSUE TITLE
Windows error: concurrently --kill-others "npm run hot-server" "npm run start-hot"

### ISSUE THREAD

**Issue by aisbergde** [billyvg/pokemon-journal#11]
Windows 10: When I open a command line window and try to run as described in the instruction I get an error:
command "concurrently" is wrong or missing
concurrently --kill-others "npm run hot-server" "npm run start-hot"

D:\Git_Repositories\pokemon-journal>npm run dev

> pokemon-journal@0.0.3 dev D:\Git_Repositories\pokemon-journal
> concurrently --kill-others "npm run hot-server" "npm run start-hot"

Der Befehl "concurrently" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "run" "dev"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! pokemon-journal@0.0.3 dev: `concurrently --kill-others "npm run hot-server" "npm run start-hot"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pokemon-journal@0.0.3 dev script 'concurrently --kill-others "npm run hot-server" "npm run start-hot"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pokemon-journal package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     concurrently --kill-others "npm run hot-server" "npm run start-hot"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pokemon-journal
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pokemon-journal
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Git_Repositories\pokemon-journal\npm-debug.log

D:\Git_Repositories\pokemon-journal>

I never used Node befor but installed especially to try this pokemon-jounal.

**Comment by billyvg** [comment]
`npm install` is needed before running

**Comment by aisbergde** [comment]
I am not able to get this work on windows. Only the prebuild version works, but it was created 2 weeks ago and I have no idea how to get or build a newer version. The prebuild version stopped to work (issue #27)
