### ISSUE TITLE
Help installing pokemon journal

### ISSUE THREAD

**Issue by spitfirebt** [billyvg/pokemon-journal#13]
Hey i need help installing pokemon journal. I installed git and node software. I used git and cloned it to a folder on my computer. Iam now lost on how to do the setup where i install the software "cd pokemon-journal && npm install" .  so help on this would be much appreciated Thx

**Comment by rickycc** [comment]
Instruction from this site might be useful.
[http://www.pokemongoprotips.com/pokemon-go-hack-how-to-list-hidden-iv-stats-for-all-your-pokemon/](url)

**Comment by billyvg** [comment]
You can download a pre-built release here: https://github.com/billyvg/pokemon-journal/releases
