### ISSUE TITLE
Failure to launch on Ubuntu 16.04 64-bit

### ISSUE THREAD

**Issue by UltimaN3rd** [billyvg/pokemon-journal#14]
Hi,

The debug log is attached.
I installed and used the command "npm run dev" and got this:

/pokemon-journal-master$ npm run dev
[npm-debug.txt](https://github.com/billyvg/pokemon-journal/files/407158/npm-debug.txt)

> pokemon-journal@0.1.2 dev /home/ultiman3rd/Downloads/pokemon-journal-master
> concurrently --kill-others "npm run hot-server" "npm run start-hot"

/usr/bin/env: ‘node’: No such file or directory

npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "dev"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! pokemon-journal@0.1.2 dev: `concurrently --kill-others "npm run hot-server" "npm run start-hot"`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the pokemon-journal@0.1.2 dev script 'concurrently --kill-others "npm run hot-server" "npm run start-hot"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pokemon-journal package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     concurrently --kill-others "npm run hot-server" "npm run start-hot"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pokemon-journal
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pokemon-journal
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ultiman3rd/Downloads/pokemon-journal-master/npm-debug.log

**Comment by billyvg** [comment]
Looks like ubuntu's node binary is named `nodejs` but it's expecting it to be `node`

You can just symlink it `ln -s /usr/bin/nodejs /usr/bin/node`

**Comment by UltimaN3rd** [comment]
Thanks, that fixed it! It listened on http://localhost:3000 and built a webpack and. . . Did nothing else. I guess a GUI is supposed to pop up? I scrolled up and there were some new errors so here's the new log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs',
1 verbose cli   '/home/ultiman3rd/Downloads/pokemon-journal-master/node_modules/.bin/npm',
1 verbose cli   'run',
1 verbose cli   'start-hot' ]
2 info using npm@3.10.5
3 info using node@v4.2.6
4 verbose run-script [ 'prestart-hot', 'start-hot', 'poststart-hot' ]
5 info lifecycle pokemon-journal@0.1.2~prestart-hot: pokemon-journal@0.1.2
6 silly lifecycle pokemon-journal@0.1.2~prestart-hot: no script for prestart-hot, continuing
7 info lifecycle pokemon-journal@0.1.2~start-hot: pokemon-journal@0.1.2
8 verbose lifecycle pokemon-journal@0.1.2~start-hot: unsafe-perm in lifecycle true
9 verbose lifecycle pokemon-journal@0.1.2~start-hot: PATH: /home/ultiman3rd/Downloads/pokemon-journal-master/node_modules/npm/bin/node-gyp-bin:/home/ultiman3rd/Downloads/pokemon-journal-master/node_modules/.bin:/usr/bin:/usr/share/npm/bin/node-gyp-bin:/home/ultiman3rd/Downloads/pokemon-journal-master/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
10 verbose lifecycle pokemon-journal@0.1.2~start-hot: CWD: /home/ultiman3rd/Downloads/pokemon-journal-master
11 silly lifecycle pokemon-journal@0.1.2~start-hot: Args: [ '-c',
11 silly lifecycle   'cross-env HOT=1 NODE_ENV=development electron -r babel-register -r babel-polyfill ./main.development' ]
12 silly lifecycle pokemon-journal@0.1.2~start-hot: Returned: code: 1  signal: null
13 info lifecycle pokemon-journal@0.1.2~start-hot: Failed to exec start-hot script
14 verbose stack Error: pokemon-journal@0.1.2 start-hot: `cross-env HOT=1 NODE_ENV=development electron -r babel-register -r babel-polyfill ./main.development`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/home/ultiman3rd/Downloads/pokemon-journal-master/node_modules/npm/lib/utils/lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/home/ultiman3rd/Downloads/pokemon-journal-master/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:821:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid pokemon-journal@0.1.2
16 verbose cwd /home/ultiman3rd/Downloads/pokemon-journal-master
17 error Linux 4.4.0-31-generic
18 error argv "/usr/bin/nodejs" "/home/ultiman3rd/Downloads/pokemon-journal-master/node_modules/.bin/npm" "run" "start-hot"
19 error node v4.2.6
20 error npm  v3.10.5
21 error code ELIFECYCLE
22 error pokemon-journal@0.1.2 start-hot: `cross-env HOT=1 NODE_ENV=development electron -r babel-register -r babel-polyfill ./main.development`
22 error Exit status 1
23 error Failed at the pokemon-journal@0.1.2 start-hot script 'cross-env HOT=1 NODE_ENV=development electron -r babel-register -r babel-polyfill ./main.development'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the pokemon-journal package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     cross-env HOT=1 NODE_ENV=development electron -r babel-register -r babel-polyfill ./main.development
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs pokemon-journal
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls pokemon-journal
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by billyvg** [comment]
Did you `npm install`?

I have not tested on node 4.x, you could try upgrading node or downloading a built linux package here: https://github.com/billyvg/pokemon-journal/releases

**Comment by UltimaN3rd** [comment]
I downloaded the Linux_x64 build and it launched right away :+1: Now I can't figure out how to login with Google 0.o I feel like I'm missing something obvious but I tried entering my Google account + password + location, hit the Login button and nothing happened. I made sure Google was selected instead of PTC.

**Comment by Tivoli** [comment]
If you are using google 2fa you need to make an app password to use. You can create one at https://security.google.com/settings/security/apppasswords

**Comment by billyvg** [comment]
Ah, that build is an old build with outdated API that was broken with one of Niantic's last updates. I am on slow internet so may not be able to update until tomorrow

**Comment by UltimaN3rd** [comment]
No worries - will you reply here when a new build is up? If not I'll just check on that page tomorrow :) Thanks a lot for the help!

**Comment by billyvg** [comment]
Released https://github.com/billyvg/pokemon-journal/releases/tag/v0.1.3

**Comment by UltimaN3rd** [comment]
Thanks! I've got the app running now :+1:
