### ISSUE TITLE
Fail to start on ubuntu 14.04.5 LTS

### ISSUE THREAD

**Issue by francesco-tran** [billyvg/pokemon-journal#15]
Hello,

I just installed, resolved all missing dependencies and run, attached is my logfile.
I am using nodejs 6.3.1 and npm 3.10.3

Thanks

> 0 info it worked if it ends with ok
> 1 verbose cli [ '/home/ubuntu/.nvm/versions/node/v6.3.1/bin/node',
> 1 verbose cli   '/home/ubuntu/pokemon-journal/node_modules/.bin/npm',
> 1 verbose cli   'run',
> 1 verbose cli   'start-hot' ]
> 2 info using npm@3.10.5
> 3 info using node@v6.3.1
> 4 verbose run-script [ 'prestart-hot', 'start-hot', 'poststart-hot' ]
> 5 info lifecycle pokemon-journal@0.1.2~prestart-hot: pokemon-journal@0.1.2
> 6 silly lifecycle pokemon-journal@0.1.2~prestart-hot: no script for prestart-hot, continuing
> 7 info lifecycle pokemon-journal@0.1.2~start-hot: pokemon-journal@0.1.2
> 8 verbose lifecycle pokemon-journal@0.1.2~start-hot: unsafe-perm in lifecycle true
> 9 verbose lifecycle pokemon-journal@0.1.2~start-hot: PATH: /home/ubuntu/pokemon-journal/node_modules/npm/bin/node-gyp-bin:/home/ubuntu/pokemon-journal/node_modules/.bin:/home/ubuntu/.nvm/versions/node/$
> 10 verbose lifecycle pokemon-journal@0.1.2~start-hot: CWD: /home/ubuntu/pokemon-journal
> 11 silly lifecycle pokemon-journal@0.1.2~start-hot: Args: [ '-c',
> 11 silly lifecycle   'cross-env HOT=1 NODE_ENV=development electron -r babel-register -r babel-polyfill ./main.development' ]
> 12 silly lifecycle pokemon-journal@0.1.2~start-hot: Returned: code: 1  signal: null
> 13 info lifecycle pokemon-journal@0.1.2~start-hot: Failed to exec start-hot script
> 14 verbose stack Error: pokemon-journal@0.1.2 start-hot: `cross-env HOT=1 NODE_ENV=development electron -r babel-register -r babel-polyfill ./main.development`
> 14 verbose stack Exit status 1
> 14 verbose stack     at EventEmitter.<anonymous> (/home/ubuntu/pokemon-journal/node_modules/npm/lib/utils/lifecycle.js:242:16)
> 14 verbose stack     at emitTwo (events.js:106:13)
> 14 verbose stack     at EventEmitter.emit (events.js:191:7)
> 14 verbose stack     at ChildProcess.<anonymous> (/home/ubuntu/pokemon-journal/node_modules/npm/lib/utils/spawn.js:40:14)
> 14 verbose stack     at emitTwo (events.js:106:13)
> 14 verbose stack     at ChildProcess.emit (events.js:191:7)
> 14 verbose stack     at maybeClose (internal/child_process.js:852:16)
> 14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
> 15 verbose pkgid pokemon-journal@0.1.2
> 16 verbose cwd /home/ubuntu/pokemon-journal
> 17 error Linux 3.13.0-91-generic
> 18 error argv "/home/ubuntu/.nvm/versions/node/v6.3.1/bin/node" "/home/ubuntu/pokemon-journal/node_modules/.bin/npm" "run" "start-hot"
> 19 error node v6.3.1
> 20 error npm  v3.10.5
> 21 error code ELIFECYCLE
> 22 error pokemon-journal@0.1.2 start-hot: `cross-env HOT=1 NODE_ENV=development electron -r babel-register -r babel-polyfill ./main.development`
> 22 error Exit status 1
> 23 error Failed at the pokemon-journal@0.1.2 start-hot script 'cross-env HOT=1 NODE_ENV=development electron -r babel-register -r babel-polyfill ./main.development'.
> 23 error Make sure you have the latest version of node.js and npm installed.
> 23 error If you do, this is most likely a problem with the pokemon-journal package,
> 23 error not with npm itself.
> 23 error Tell the author that this fails on your system:
> 23 error     cross-env HOT=1 NODE_ENV=development electron -r babel-register -r babel-polyfill ./main.development
> 23 error You can get information on how to open an issue for this project with:
> 23 error     npm bugs pokemon-journal
> 23 error Or if that isn't available, you can get their info via:
> 23 error     npm owner ls pokemon-journal
> 23 error There is likely additional logging output above.
> 24 verbose exit [ 1, true ]

**Comment by billyvg** [comment]
If you are just trying to run it, please download from the [releases](https://github.com/billyvg/pokemon-journal/releases)

**Comment by francesco-tran** [comment]
Thanks, I managed to run it.
