### ISSUE TITLE
Linux, failure to install / run

### ISSUE THREAD

**Issue by JohnnyBigoud** [billyvg/pokemon-journal#16]
Hello,

I've read the other issues, but no one seems to have the issues that I'm facing. I'm not really into all that coding stuff so I might do some steps wrong.

According to my understanding there is two ways to use this app: 
1/ Downloading the code, and proceed to install it throught npm intall & run it with npm run dev. 
2/ Downloading one of the releases (the linux one in my case), extracting it and running the program by ./PokemonJournal

As I don't really intend to make changes to the code, I'd go to the second option. However when I launch the program, I get:
![image](https://cloud.githubusercontent.com/assets/20937336/17537668/ea609d8c-5e9e-11e6-809d-de09deab599b.png)

I'd really appreciate a little help. I really don't undertand how to solve the issue. Am I supposed to retrieve other librairies?

In any case, thank you very much for sharing you work.

**Comment by Tivoli** [comment]
Looks like a missing lib, try `sudo apt-get install libxss1`

**Comment by JohnnyBigoud** [comment]
Yes, I had this library missing and few others. I got them. Now I get the login screen. However when I input my google username and password, nothing happens. I'll look into it tomorow.

Thank you for your quick answer anyway.

**Comment by billyvg** [comment]
I have uploaded some pre-built windows packages here https://github.com/billyvg/pokemon-journal/releases
