### ISSUE TITLE
Error logging in

### ISSUE THREAD

**Issue by PJPOSEY** [billyvg/pokemon-journal#29]
Logged in, this error message appear :
![image](https://cloud.githubusercontent.com/assets/21177791/17861867/b0d361da-688a-11e6-8eb9-088d50c94826.png)

**Comment by Xetius** [comment]
I'm having the same issue.

I've copied the console log output here http://pastebin.com/pNCSrpZy

**Comment by billyvg** [comment]
Are you using prebuilt or dev?

Make sure you run `npm install` if you are using dev version as pogobuf library was recently updated

**Comment by PJPOSEY** [comment]
I'm using prebuilt. Seems like I Installed the other windows prebuilt (for ia32) and it worked again. Weird...  x64 worked very well (and i'm on a 64 pc).

Thank you for your reactivity.

However now the "Recent" function seems to have problems. It put first POkemons that i caught one month ago.

**Comment by billyvg** [comment]
Recent fixed in latest build https://github.com/billyvg/pokemon-journal/releases/tag/0.2.2
