### ISSUE TITLE
Error on "npm run dev"

### ISSUE THREAD

**Issue by Nicte** [billyvg/pokemon-journal#3]
When running the tool npm gives an error:

![image](https://cloud.githubusercontent.com/assets/4835465/17155056/e5aad13e-5383-11e6-9607-38aefec67e29.png)

**Comment by billyvg** [comment]
It looks like you already have something running on port 3000. You could try `npm start`

**Comment by Nicte** [comment]
npm start gives:

![image](https://cloud.githubusercontent.com/assets/4835465/17184464/a653bfc4-542c-11e6-9df6-c735c054dcea.png)

Also, I check just in case but i have nothing running at "localhost:3000". Not sure exactly what is happening. I change the code to run in 3001 and that fixed it (I had to change it in couple of places, so maybe we want to add this as a parameter maybe? -p 3001?)

**Comment by billyvg** [comment]
Please download and use a pre-built package here https://github.com/billyvg/pokemon-journal/releases
