### ISSUE TITLE
There is 2 different % showing up 

### ISSUE THREAD

**Issue by TWIISTED-STUDIOS** [billyvg/pokemon-journal#31]
i just got round to trying the new app and have noticed there is two different percentages now showing on the app how does one use this or is it calculating the ivs in correctly now

**Comment by beejaymay** [comment]
The % next to the CP value indicates the pokemon's CP relative to its maximum potential CP (pokemon has CP of 750, its max CP at its level is 1000, the value will be 75%)

The % next to the IVs indicates the pokemon's combined IV relative to perfection (a 14/14/15 pokemon  has a total of 43 out of 45 total, for 95%).

The reason it's useful to have both percentages is that the attack IV is disproportionately weighted in the CP calculation. A pokemon with high atk IV and low def and stam IVs can still have a pretty high CP.

**Comment by TWIISTED-STUDIOS** [comment]
Thank you that makes things so much more clear now I understand why that's actually a good idea to have both

Get Outlook for Androidhttps://aka.ms/ghei36

On Thu, Aug 25, 2016 at 3:49 PM +0100, "B.J. May" <notifications@github.com<mailto:notifications@github.com>> wrote:

The % next to the CP value indicates the pokemon's CP relative to its maximum potential CP (pokemon has CP of 750, its max CP at its level is 1000, the value will be 75%)

The % next to the IVs indicates the pokemon's combined IV relative to perfection (a 14/14/15 pokemon has a total of 43 out of 45 total, for 95%).

The reason it's useful to have both percentages is that the attack IV is disproportionately weighted in the CP calculation. A pokemon with high atk IV and low def and stam IVs can still have a pretty high CP.

##
