### ISSUE TITLE
AssertionError: Current npm version is not supported for development, expected "4.1.2" to satisfy "2.x || 3.x"

### ISSUE THREAD

**Issue by aisbergde** [billyvg/pokemon-journal#38]
I pulled the latest version with TortoiseGit
I installed the latest node
I executed this to get the latest npm: "npm install npm@latest -g"
Now my versions are:
node v6.9.5
npm v4.1.2

I executed "npm install" in the project folder "D:\Git_Repositories\pokemon-journal"
First time a lot of required modules have been installed but at the end I get an error. Then I tried again but got the same error. It looks like some problems with the npm version. But I have no idea what I should do now.

D:\Git_Repositories\pokemon-journal>npm install

> pokemon-journal@0.2.2 postinstall D:\Git_Repositories\pokemon-journal
> node node_modules/fbjs-scripts/node/check-dev-engines.js package.json

assert.js:85
  throw new assert.AssertionError({
  ^
AssertionError: Current npm version is not supported for development, expected "4.1.2" to satisfy "2.x || 3.x".
    at D:\Git_Repositories\pokemon-journal\node_modules\fbjs-scripts\node\check-dev-engines.js:57:5
    at ChildProcess.exithandler (child_process.js:197:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Germo\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.9.5
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! pokemon-journal@0.2.2 postinstall: `node node_modules/fbjs-scripts/node/check-dev-engines.js package.json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pokemon-journal@0.2.2 postinstall script 'node node_modules/fbjs-scripts/node/check-dev-engines.js package.json'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pokemon-journal package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/fbjs-scripts/node/check-dev-engines.js package.json
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pokemon-journal
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pokemon-journal
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Git_Repositories\pokemon-journal\npm-debug.log

D:\Git_Repositories\pokemon-journal>

**Comment by aisbergde** [comment]
I removed the latest nmp version, now my versions are
**node v6.9.5
npm  v3.10.10**

I execute
**D:\Git_Repositories\pokemon-journal>npm install**

> pokemon-journal@0.2.2 postinstall D:\Git_Repositories\pokemon-journal
> node node_modules/fbjs-scripts/node/check-dev-engines.js package.json

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})


No more errors now, but nothing more happens, **I can't find the compiled application.**

When I execute:
**D:\Git_Repositories\pokemon-journal>npm run dev**

then something happens, finally the app opens in a kind of debug modus, there are some additional windows on the right (Developer tools). And there are 2 warnings and one error:
**A Parser-blocking, cross-origin script, http://localhost:3000/dist/bundle.js, is invoked via document.write. This may be blocked by the browser if the device has poor network connectivity.
http://localhost:3000/dist/bundle.js Failed to load resource: the server responded with a status of 404 (Not Found)**

But there is no login window available for connecting to a server.

I also tried a global install, but in this case some moduls are missing and it always ends in a rollback of the install:

**D:\Git_Repositories\pokemon-journal>npm install -g**
npm WARN deprecated electron-prebuilt@1.4.13: electron-prebuilt has been renamed to electron. For more details, see http://electron.atom.io/blog/2016/08/16/npm-install-electron
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
C:\Users\Germo\AppData\Roaming\npm\electron -> C:\Users\Germo\AppData\Roaming\npm\node_modules\pokemon-journal\node_modules\.bin\electron

> electron-prebuilt@1.4.13 postinstall C:\Users\Germo\AppData\Roaming\npm\node_modules\pokemon-journal\node_modules\electron-prebuilt
> node install.js


> pokemon-journal@0.2.2 postinstall C:\Users\Germo\AppData\Roaming\npm\node_modules\pokemon-journal
> node node_modules/fbjs-scripts/node/check-dev-engines.js package.json

module.js:471
    throw err;
    ^

Error: Cannot find module 'C:\Users\Germo\AppData\Roaming\npm\node_modules\pokemon-journal\node_modules\fbjs-scripts\node\check-dev-engines.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
C:\Users\Germo\AppData\Roaming\npm
`-- (empty)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\pokemon-journal\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN co-mocha@1.2.0 requires a peer of mocha@>=1.18 <4 but none was installed.
npm WARN eslint-plugin-import@1.16.0 requires a peer of eslint@2.x - 3.x but none was installed.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! pokemon-journal@0.2.2 postinstall: `node node_modules/fbjs-scripts/node/check-dev-engines.js package.json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pokemon-journal@0.2.2 postinstall script 'node node_modules/fbjs-scripts/node/check-dev-engines.js package.json'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pokemon-journal package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/fbjs-scripts/node/check-dev-engines.js package.json
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pokemon-journal
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pokemon-journal
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Git_Repositories\pokemon-journal\npm-debug.log
npm ERR! code 1


I have really no idea what else I could try and how to get the jounal work again after 2. generation pokemons have been added.
**Could some one please provide a working pre-compiled Windows version?**

[npm-debug.zip](https://github.com/billyvg/pokemon-journal/files/785803/npm-debug.zip)

**Comment by billyvg** [comment]
I can try to see what's going on this weekend. You can also try using virtualbox, might take less work than trying to get it running on windows.

**Comment by mgedwards** [comment]
Also,  you can try deleting the dev engines section of the package.json (after you update to the latest code)

**Comment by aisbergde** [comment]
If you suggest to try VirtualBox: do you mean to run a Unix system in the VM and to try to get the journal running in this environment?

**Comment by aisbergde** [comment]
I neer used Unix or Linux. I installed VirtualBox, created an ubuntu 64 bit VM, but it looks like there is a lt to do before I get this running :-(
Are there some preconfigured VirtualBox VM's you can recommend which I could use to compile the pokemon-Journal?

**Comment by aisbergde** [comment]
I tried on my Windows System again:
got the latest pull from git
executed:
npm install
executed:
npm run dev

Now I get the application, I can login, but I get time outs and nothing is shown.

BTW, is the "npm run dev" the only way to get it executed and is this allways build at runtime?
Or is there a way to generate an exe so I can put on my childrens PC so they can use it?

**Comment by aisbergde** [comment]
Before I login I get 2 warnings and 4 errors:

A Parser-blocking, cross-origin script, http://localhost:3000/dist/bundle.js, is invoked via document.write. This may be blocked by the browser if the device has poor network connectivity.

warning.js?8a56:36Warning: Unknown prop `autowidth` on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in div (created by TextField)
    in TextField (created by SelectField)
    in SelectField (created by Login)
    in div (created by Login)
    in form (created by Login)
    in Login (created by MobXStoreInjector)
    in MobXStoreInjector (created by Home)
    in div (created by Home)
    in Home (created by HomePage)
    in div (created by HomePage)
    in HomePage (created by MobXStoreInjector)
    in MobXStoreInjector (created by RouterContext)
    in div (created by App)
    in MuiThemeProvider (created by App)
    in App (created by RouterContext)
    in RouterContext (created by Router)
    in Router
    in Provider
    in ProviderprintWarning @ warning.js?8a56:36
warning.js?8a56:36Warning: Failed prop type: The prop `message` is marked as required in `Snackbar`, but its value is `undefined`.
    in Snackbar (created by Notifications)
    in Notifications (created by MobXStoreInjector)
    in MobXStoreInjector (created by HomePage)
    in div (created by HomePage)
    in HomePage (created by MobXStoreInjector)
    in MobXStoreInjector (created by RouterContext)
    in div (created by App)
    in MuiThemeProvider (created by App)
    in App (created by RouterContext)
    in RouterContext (created by Router)
    in Router
    in Provider
    in ProviderprintWarning @ warning.js?8a56:36
warning.js?8a56:36Warning: Failed prop type: The prop `message` is marked as required in `SnackbarBody`, but its value is `undefined`.
    in SnackbarBody (created by WithWidth)
    in WithWidth (created by Snackbar)
    in div (created by Snackbar)
    in ClickAwayListener (created by Snackbar)
    in Snackbar (created by Notifications)
    in Notifications (created by MobXStoreInjector)
    in MobXStoreInjector (created by HomePage)
    in div (created by HomePage)
    in HomePage (created by MobXStoreInjector)
    in MobXStoreInjector (created by RouterContext)
    in div (created by App)
    in MuiThemeProvider (created by App)
    in App (created by RouterContext)
    in RouterContext (created by Router)
    in Router
    in Provider
    in ProviderprintWarning @ warning.js?8a56:36
client.js?207a:67[HMR] connected
warning.js?8a56:36Warning: TextField is changing an uncontrolled input of type text to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-componentsprintWarning @ warning.js?8a56:36


But I can login.
And I get these 2 errors:

authStore.js?0d74:88 Error logging in  Error: operation timed out after 4675 ms, 5 tries with error: Fetching RPC endpoint failed, received status code 100
    at D:\Git_Repositories\pokemon-journal\node_modules\bluebird-retry\lib\bluebird-retry.js:109:35
    at process._tickCallback (internal/process/next_tick.js:103:7)
From previous event:
    at try_once (D:\Git_Repositories\pokemon-journal\node_modules\bluebird-retry\lib\bluebird-retry.js:81:14)
From previous event:
    at D:\Git_Repositories\pokemon-journal\node_modules\bluebird-retry\lib\bluebird-retry.js:118:53
From previous event:
    at try_once (D:\Git_Repositories\pokemon-journal\node_modules\bluebird-retry\lib\bluebird-retry.js:81:14)
    at retry (D:\Git_Repositories\pokemon-journal\node_modules\bluebird-retry\lib\bluebird-retry.js:123:12)
    at EventEmitter.Client.callRPC (D:\Git_Repositories\pokemon-journal\node_modules\pogobuf\pogobuf\pogobuf.client.js:1013:16)
    at EventEmitter.Client.callOrChain (D:\Git_Repositories\pokemon-journal\node_modules\pogobuf\pogobuf\pogobuf.client.js:837:25)
    at EventEmitter.Client.downloadSettings (D:\Git_Repositories\pokemon-journal\node_modules\pogobuf\pogobuf\pogobuf.client.js:199:21)
    at promise.then (D:\Git_Repositories\pokemon-journal\node_modules\pogobuf\pogobuf\pogobuf.client.js:119:47)
    at tryCatcher (D:\Git_Repositories\pokemon-journal\node_modules\pogobuf\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\Git_Repositories\pokemon-journal\node_modules\pogobuf\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (D:\Git_Repositories\pokemon-journal\node_modules\pogobuf\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromiseCtx (D:\Git_Repositories\pokemon-journal\node_modules\pogobuf\node_modules\bluebird\js\release\promise.js:604:10)
    at Async._drainQueue (D:\Git_Repositories\pokemon-journal\node_modules\pogobuf\node_modules\bluebird\js\release\async.js:138:12)
    at Async._drainQueues (D:\Git_Repositories\pokemon-journal\node_modules\pogobuf\node_modules\bluebird\js\release\async.js:143:10)
    at Async.drainQueues (D:\Git_Repositories\pokemon-journal\node_modules\pogobuf\node_modules\bluebird\js\release\async.js:17:14)
    at process._tickCallback (internal/process/next_tick.js:103:7)(anonymous function) @ authStore.js?0d74:88_tickCallback @ internal/process/next_tick.js:103


authStore.js?0d74:153 Error retrieving inventory Error: operation timed out after 4677 ms, 5 tries with 
error: Fetching RPC endpoint failed, received status code 100
    at D:\Git_Repositories\pokemon-journal\node_modules\bluebird-retry\lib\bluebird-retry.js:109:35
    at process._tickCallback (internal/process/next_tick.js:103:7)
From previous event:
    at try_once (D:\Git_Repositories\pokemon-journal\node_modules\bluebird-retry\lib\bluebird-retry.js:81:14)
From previous event:
    at D:\Git_Repositories\pokemon-journal\node_modules\bluebird-retry\lib\bluebird-retry.js:118:53
From previous event:
    at try_once (D:\Git_Repositories\pokemon-journal\node_modules\bluebird-retry\lib\bluebird-retry.js:81:14)
    at retry (D:\Git_Repositories\pokemon-journal\node_modules\bluebird-retry\lib\bluebird-retry.js:123:12)
    at EventEmitter.Client.callRPC (D:\Git_Repositories\pokemon-journal\node_modules\pogobuf\pogobuf\pogobuf.client.js:1013:16)
    at EventEmitter.Client.callOrChain (D:\Git_Repositories\pokemon-journal\node_modules\pogobuf\pogobuf\pogobuf.client.js:837:25)
    at EventEmitter.Client.downloadSettings (D:\Git_Repositories\pokemon-journal\node_modules\pogobuf\pogobuf\pogobuf.client.js:199:21)
    at promise.then (D:\Git_Repositories\pokemon-journal\node_modules\pogobuf\pogobuf\pogobuf.client.js:119:47)
    at tryCatcher (D:\Git_Repositories\pokemon-journal\node_modules\pogobuf\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\Git_Repositories\pokemon-journal\node_modules\pogobuf\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (D:\Git_Repositories\pokemon-journal\node_modules\pogobuf\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromiseCtx (D:\Git_Repositories\pokemon-journal\node_modules\pogobuf\node_modules\bluebird\js\release\promise.js:604:10)
    at Async._drainQueue (D:\Git_Repositories\pokemon-journal\node_modules\pogobuf\node_modules\bluebird\js\release\async.js:138:12)
    at Async._drainQueues (D:\Git_Repositories\pokemon-journal\node_modules\pogobuf\node_modules\bluebird\js\release\async.js:143:10)
    at Async.drainQueues (D:\Git_Repositories\pokemon-journal\node_modules\pogobuf\node_modules\bluebird\js\release\async.js:17:14)
    at process._tickCallback (internal/process/next_tick.js:103:7)(anonymous function) @ authStore.js?0d74:153_tickCallback @ internal/process/next_tick.js:103

**Comment by mgedwards** [comment]
Never mind - seems to be that the api has been updated. Will try to find out what has changed,

**Comment by billyvg** [comment]
I updated the project dependencies so you can use the latest npm version, updated pogobuf library as well, see if this helps (I don't remember my login info to test, oops).

I'm also setting up automated windows builds

**Comment by aisbergde** [comment]
"npm install" works fine now
"npm run dev" works fine now, I can loog in, pokemons are showing, thank you for fixing!

This is nothing what I could give to my children to use the journal. I still don't understand how to create a windows executable or something what can be executed without building it each time, maybe it was created when I executed "npm run dev", but in this case I don't know where to search and what to call.

On the other hand a few days ago I found an android app (IV Go) which also logs into the server and gets this information in a similair way. My children installed this app and they are happy with this solution too :-)

**Comment by billyvg** [comment]
You can download an executable here: https://github.com/billyvg/pokemon-journal/releases

**Comment by aisbergde** [comment]
Hallo billyvg
Thank you for the new setup! But I get the same error a got 3 days ago (details see above)
"Error fetching inventory: Error: operation timed out after 4676 ms, 5 tries"
on the other hand, when I executed "npm run dev" after pull from GIT 6 hours ago then all worked fine. But my compilation (?) was done not with node 7, but with node v6.9.5

**Comment by billyvg** [comment]
Odd, well you can build your own package with `npm run package-win`
