### ISSUE TITLE
Can't login with Google

### ISSUE THREAD

**Issue by AniLabXTeam** [billyvg/pokemon-journal#4]
I get this in console when trying to login with Google
http://imgur.com/zZjkWBx

With PTC it's seems fine.

**Comment by AniLabXTeam** [comment]
Used another google acc. It's working. But why it crashes with my main acc? Maybe 2-step auth?

**Comment by AniLabXTeam** [comment]
Logged in using "app pasword".
But pokemon list empty and in console i see many errors -_-

**Comment by billyvg** [comment]
Can you post the errors you're seeing in console?

**Comment by AniLabXTeam** [comment]
Yep. Here is - http://imgur.com/dGnPxYy

**Comment by AniLabXTeam** [comment]
Oh. I see pokemons on my PTC acc. By don't see on Google.

**Comment by billyvg** [comment]
I've changed the pokemon go API package, give v0.0.3 a shot.

**Comment by AniLabXTeam** [comment]
It's working now. Thank you!
May I ask? Can you add ability to transfer pokemons to candies dirrectly from app? I have slow phone and transfering is really pain for me -_-

**Comment by billyvg** [comment]
I was thinking about adding the ability to transfer and rename, but not sure yet. For me it's an issue about how kosher it is to use the API for "write" operations vs just reading data.
