### ISSUE TITLE
Location Field

### ISSUE THREAD

**Issue by ayublin** [billyvg/pokemon-journal#5]
What is the accepted location string format? Will "lat, lng" works? Thanks!

**Comment by billyvg** [comment]
I'm not entirely sure, I've been using strings -- I'm going to release an update so that it uses geolocation to set your location though

**Comment by ayublin** [comment]
After taking a look at the code and reading on the pokemon go node api github page, it seems like it took a string of address.

That sounds nice, but it would be perfect if you can add it as a checkbox and left the location text input as it is. Thanks!
