### ISSUE TITLE
Percentage calculated wrongly?

### ISSUE THREAD

**Issue by Nicte** [billyvg/pokemon-journal#6]
So I was checking the IV's of my mons and something struct me as strange. I have a kabuto and a Magikarp with:

Kabuto: 15/13/15       =    43  (95%)
Magikarp: 13/15/15    =   43  (95%)

But as you can see, the tool is giving the Magikarp a 92% (the same as 14/15/13 Weedle):

![image](https://cloud.githubusercontent.com/assets/4835465/17185006/6bf05092-542f-11e6-8b5c-1e4bb2fd8ea0.png)

Any idea why? Is this a bug, or am I missing something?

**Comment by Tivoli** [comment]
There's more to the calculation than just IV, this is the formula for calculating max CP https://www.reddit.com/r/TheSilphRoad/comments/4t7r4d/exact_pokemon_cp_formula/ so it's not just IV, it's also the cp multiplier which can vary based on capture as well as base stats.

**Comment by Nicte** [comment]
Ok, so the Max CP is not based only on IV's, but I couldn't find a reference for the "cp multiplier which can vary based on capture". Also, the API (at least the npm package that this tool uses) doesn't return a "cp multiplier" field that I can see:

`{
    "pokemon_id": 84,
    "cp": 103,
    "stamina": 22,
    "individual_attack": 10,
    "individual_defense": 10,
    "individual_stamina": 7,
    "creation_time_ms": {
      "low": 595943660,
      "high": 342,
      "unsigned": true
    }
  }`

So you are saying that this 2 Zubats can have equal percentage even if one has total IV's of 39 and the other of 36?:

![image](https://cloud.githubusercontent.com/assets/4835465/17186136/3c398b16-5434-11e6-9891-c4ca4031d369.png)

Is this due to the "cp multiplier" being different for both of them?

Also, the sorting option says "IV" so maybe that is why it looks weird to me.

Again, great work with the tool, just giving some feedback here! :D

**Comment by wildleaf** [comment]
Does this make sense? IV(14/9/9) and have 100%? Meaning it can be more than 100%? what's the maximum in that case?

![screen shot 2016-08-08 at 5 34 21 pm](https://cloud.githubusercontent.com/assets/1013099/17498682/76267ede-5d8e-11e6-8282-9533b4bceb5e.png)

**Comment by wildleaf** [comment]
I got it now. The 100% cp was because the precision of convertIV()
Fix would be moving the divided by ten out of Math.floor(). Need to compare the max and current cp first, calculate the cp percentage based on that, then floor the current cp again for display. This way I think it is more accurate.

return Math.floor(Math.pow(stamina, 0.5) \* attack \* Math.pow(defense, 0.5))/10;

In my Paras example. MaxCP=12.9, currentCP=12.1, minCP = 9.8 percentage should be 74%

**Comment by onilton** [comment]
@wildleaf But your formula seems different from Reddit's one:

`CP = MAX(10, FLOOR(Stamina^0.5 * Attack * Def^0.5 / 10))`

Yours seems  like

`FLOOR(Stamina^0.5 * Attack * Def^0.5) / 10`  instead of

`FLOOR(Stamina0.5 * Attack * Def0.5 / 10)`

**Comment by wildleaf** [comment]
@onilton This is only adding additional decimal point to the CP.  This is only used in the calculation of cp percentage (currCp - minCP)/(maxCp - minCP). Without the extra precision, the result is going to be off.
