### ISSUE TITLE
What is the "location" field?

### ISSUE THREAD

**Issue by erikfox** [billyvg/pokemon-journal#8]
What is an acceptable input?

**Comment by billyvg** [comment]
Any address string (zipcode, address, city/state, etc)

Note, I may be getting rid of this field since it doesn't seem necessary for retrieving contents of player's inventory.

**Comment by rickycc** [comment]
According to [http://www.pokemongoprotips.com/pokemon-go-hack-how-to-list-hidden-iv-stats-for-all-your-pokemon/](url) your app might teleport the user. With the imminent harsher ban on spoofing, are we expose to any risk in using the application?

**Comment by billyvg** [comment]
There's always risk in using the API outside of the app. The API calls that we use don't require a "location" parameter to be sent, so we no longer send anything to tell them our location (4abea3e7fc83c758573442f475c7647b7303b5ae).
