### ISSUE TITLE
`node-gyp rebuild` Error when running 'npm run dev'

### ISSUE THREAD

**Issue by AtraSatraps** [billyvg/pokemon-journal#9]
nslog@3.0.0 install: `node-gyp rebuild`
Exit status 1

Failed at the nslog@3.0.0 install script 'node-gyp rebuild'.
Make sure you have the latest version of node.js and npm installed.
If you do, this is most likely a problem with the nslog package,
not with npm itself.
Tell the author that this fails on your system:
    node-gyp rebuild
You can get information on how to open an issue for this project with:
    npm bugs nslog
Or if that isn't available, you can get their info via:
    npm owner ls nslog
There is likely additional logging output above.

**Comment by AtraSatraps** [comment]
Newly installed node and npm, so that is unlikely the problem.

**Comment by billyvg** [comment]
What OS are you on and what version of node?

**Comment by AtraSatraps** [comment]
Windows 8.1

$ node -v
    v4.4.7

$ npm -v
    3.10.5

**Comment by billyvg** [comment]
Hmm, seems like there is an issue with building nslog on windows: https://github.com/electron/electron-rebuild/issues/15

I am currently traveling, but will try to investigate when I'm back.

**Comment by MaaRak** [comment]
I got the same error (win10, node 4.4.7, npm 3.10.5), but earlier in the build also got this:

'error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.'

Got past the error by installing [Visual C++ Build Tools 2015](http://landinghub.visualstudio.com/visual-cpp-build-tools), setting an environment variable (as per [this discussion](http://stackoverflow.com/questions/21069699/node-packages-not-building-on-windows-8-1-missing-microsoft-cpp-default-props)):

`set VCTargetsPath=C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140`

and re-running 'npm install'.

I get a different error now when running 'npm run dev' (which I'll post in a separate issue), but progress, I think.

**Comment by billyvg** [comment]
You can download and use a pre-built package here https://github.com/billyvg/pokemon-journal/releases
